import Head from "next/head";
import "./globals.css";
import React from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Geist:wght@400;700&family=Geist+Mono:wght@400&display=swap"
          rel="stylesheet"
        />
      </Head>
      <body className="antialiased">{children}</body>
    </html>
  );
}
