# Generated by Django 5.1.5 on 2025-02-03 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('toppings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaToppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzaName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizzas.pizza')),
                ('toppingName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toppings.toppings')),
            ],
        ),
    ]
